# Un minimum de théorie de la mesure


## Feuille de route

Pour pratiquer la modélisation stochastique de façon confortable, il faut des fondations et des notations cohérentes. Dans ce chapitre, nous posons le cadre pour la suite. La théorie des probabilités est née de l'interaction entre la combinatoire et les jeux de hasard (XVIIe siècle). À cette époque, l'ensemble des issues était fini, et il était légitime de penser que tout ensemble d'issues possédait une probabilité bien définie. Lorsque les mathématiciens ont commencé à pratiquer la modélisation stochastique dans différentes branches des sciences (astronomie, thermodynamique, génétique, ...), ils ont dû traiter des ensembles d'issues non dénombrables. Élaborer une définition solide de ce qu'est une loi de probabilité a pris du temps. Les progrès de la théorie de l'intégration et de la mesure au XIXe siècle et dans les premières décennies du XXe siècle ont conduit au fondement moderne de la théorie des probabilités, fondé sur la théorie de la mesure.



{{< include _packages_requirements.qmd >}}

## Univers, ensemble des parties et $\sigma$-algèbres  {#sec-tribe}

Un _univers_ est un ensemble (d'_issues_ possibles) que l'on décide d'appeler univers. L'univers est souvent noté $\Omega$. Les éléments génériques de $\Omega$ (les issues) sont notés $\omega$.

<br><p></p>

::: {#exm-universe}

Si l'on pense au lancer d'un dé comme à un phénomène aléatoire, l'ensemble des issues est l'ensemble des étiquettes des faces $\Omega = \{1, 2, 3, 4, 5, 6\}$. Si l'on lance deux dés, l'ensemble des issues est constitué des couples d'étiquettes $\Omega' = \{(1,1), (1, 2), (1, 3), \ldots, (6,6)\} =\Omega^2$.

:::

<br><p></p>


::: {#exm-unverse-hashing}

Dans le problème de hachage idéalisé (@sec-hashing), l'univers est l'ensemble des fonctions de $1, \ldots, n$ vers $1, \ldots, m$. Le cardinal de l'univers est $m^n$.

:::

<br><p></p>

Un univers peut être fini ou dénombrable, ou ne l'être pas. Si l'univers est dénombrable, tous ses sous-ensembles peuvent être appelés _événements_. On attribue des probabilités aux événements.
Si l'univers est dénombrable, il est possible d'attribuer une probabilité à chacun de ses sous-ensembles.
Lorsque l'univers n'est pas dénombrable (par exemple $\mathbb{R}$), attribuer une probabilité à tous les sous-ensembles n'est pas possible. Il faut restreindre la collection de sous-ensembles afin d'attribuer des probabilités aux membres de cette collection de façon cohérente.

Dans la suite, $2^{\Omega}$ désigne la collection de tous les sous-ensembles de $\Omega$ (l'ensemble des parties de $\Omega$).

Une collection raisonnable d'événements doit être une $\sigma$-algèbre.

<br><p></p>

::: {#def-sigalgebra}

### $\sigma$-algèbre

Étant donné un ensemble $\Omega$, une collection $\mathcal{G}$ de sous-ensembles de $\Omega$ ($\mathcal{G} \subseteq 2^{\Omega}$) est appelée $\sigma$-algèbre (une sigma-algèbre) si et seulement si

- $\mathcal{G}$ est stable par union $dénombrable$
- $\emptyset \in \mathcal{G}$
- $\mathcal{G}$ est stable par passage au complémentaire ($A \in \mathcal{G} \Rightarrow A^c = \Omega \setminus A \in \mathcal{G}$)

:::

<br><p></p>


::: {#exr-smallest-sigma-algebra-trivial}

Quelle est la plus petite $\sigma$-algèbre (au sens de l'inclusion) qui contient un sous-ensemble $A$ de $\Omega$ ?

:::

<br><p></p>

La proposition suivante montre que les $\sigma$-algèbres sont stables par les opérations ensemblistes dénombrables. On aurait pu remplacer l'union dénombrable par l'intersection dénombrable dans la définition des $\sigma$-algèbres. C'est une conséquence des lois de De Morgan :


$$
(A \cup B)^c  = A^c \cap B^c \qquad \text{et} (A \cap B)^c  = A^c \cup B^c
$$


::: {#prp-sigma-alg-intersections}

Une $\sigma$-algèbre de sous-ensembles est stable par intersections dénombrables.

:::

<br><p></p>


::: {.proof}

Pour $A \subseteq \Omega$, posons $A^c = \Omega \setminus A$.
Soient $A_1, \ldots, A_n, \ldots$ des éléments d'une $\sigma$-algèbre $\mathcal{G}$ de sous-ensembles
de $\Omega$. Pour chaque $n$, $A_n^c \in \mathcal{G}$, par définition d'une $\sigma$-algèbre,
\begin{align*}
\cap_n A_n
 & = \Big(\big(\cap_n A_n\big)^c\Big)^c \\
 & = \Big(\cup_n A_n^c\Big)^c  \qquad \text{De Morgan} \, .
\end{align*}
Par définition d'une $\sigma$-algèbre, $\cup_n A_n^c \in \mathcal{G}$, et
pour la même raison, $\Big(\cup_n A_n^c \Big)^c \in \mathcal{G}$.

:::

<br><p></p>

La proposition suivante permet de parler de la plus petite $\sigma$-algèbre contenant une collection de sous-ensembles ; cela mène à la notion de $\sigma$-algèbre engendrée.

<br><p></p>


::: {#prp-intersection-sigma-algebras}

### Intersection de $\sigma$-algèbres

L'intersection de deux $\sigma$-algèbres de sous-ensembles de $\Omega$
est une $\sigma$-algèbre de sous-ensembles de $\Omega$.

:::


<br><p></p>


::: {.proof}

Soient $\mathcal{G}$ et $\mathcal{G}'$ deux $\sigma$-algèbres de sous-ensembles
de $\Omega$. L'intersection des deux $\sigma$-algèbres est

$$
\Big\{ A : A\subseteq \Omega, A \in \mathcal{G}, A \in \mathcal{G}' \Big\}\, .
$$


:::

<br><p></p>

En fait, l'intersection d'une collection éventuellement non dénombrable de $\sigma$-algèbres
est une $\sigma$-algèbre (le vérifier).
Grâce à cette propriété, la notion de $\sigma$-algèbre engendrée par une collection de sous-ensembles est bien fondée.

::: {#lem-gen-sigma-algebra} 

### $\sigma$-algèbre engendrée

Étant donnée une collection $\mathcal{C}$ de sous-ensembles de $\Omega$, il existe une _unique plus petite $\sigma$-algèbre_ contenant tous les sous-ensembles de $\mathcal{C}$ ; on l'appelle la $\sigma$-algèbre engendrée par $\mathcal{H}$ et on la note $\sigma(\mathcal{C})$.

:::

<br><p></p>

::: {#exr-generated-sigma-algebra}

Vérifier la proposition précédente.

:::

<br><p></p>

::: {#exm-sigma-dice} 

On lance un dé, $\Omega = \{1, \ldots, 6\}$, et l'on pose $$\mathcal{H} = \Big\{\{1, 3, 5\}\Big\}\, .$$ C'est une collection constituée d'un seul événement (l'issue est impaire). L'algèbre engendrée par $\mathcal{H}$ est $$\sigma(\mathcal{H}) = \Big\{ \{1, 3, 5\}, \{2, 4, 6\}, \emptyset, \Omega \Big\} \, .$$

:::

<p>
Deux types de $\sigma$-algèbres jouent un rôle de premier plan dans un cours élémentaire de probabilités :

1. l'ensemble des parties des ensembles dénombrables ou finis.
1. les $\sigma$-algèbres boréliennes des espaces topologiques.

<p>


::: {#def-borel-sigma-algebra} 

### $\sigma$-algèbre borélienne

La $\sigma$-algèbre borélienne sur $\mathbb{R}$ est la $\sigma$-algèbre engendrée
par les _ouverts_. On la note $\mathcal{B}(\mathbb{R})$.

:::

<p>
Cette définition s'applique à tout espace topologique. Rappelons qu'une topologie
sur un ensemble $E$ est définie par une collection $\mathcal{E}$ d'_ouverts_. Cette collection
est définie par la liste de propriétés suivante :

- $\emptyset, E \in \mathcal{E}$
- Une union (_éventuellement non dénombrable_) d'éléments de $\mathcal{E}$ (d'ouverts)
appartient à $\mathcal{E}$ (est un ouvert)
- Une intersection finie d'ouverts est un ouvert.

Dans la topologie usuelle sur $\mathbb{R}$, un ensemble $A$ est ouvert si pour tout $x \in A$, il
existe $r>0$ tel que $]x-r, x+r[ \subseteq A$. Tout intervalle de la forme $]a,b[$
est ouvert (ce sont les intervalles dits ouverts).

Cette topologie se généralise à toute dimension finie $\mathbb{R}^d$.
<p>

::: {#exr-sigma-alg-open-inter}

Considérer la $\sigma$-algèbre engendrée par les intervalles ouverts de $\mathbb{R}$.
Est-ce la $\sigma$-algèbre borélienne ?

:::

::: {#exr-sigma-alge-inter-rational}

Considérer la $\sigma$-algèbre engendrée par les intervalles ouverts de $\mathbb{R}$ à bornes rationnelles.
Est-ce la $\sigma$-algèbre borélienne ?

:::

::: {#exr-sigma-open-balls}

Soit $(E,d)$ un espace métrique quelconque. La métrique $d$ définit une topologie sur $E$.
La $\sigma$-algèbre borélienne sur $(E, d)$ coïncide-t-elle avec la
$\sigma$-algèbre engendrée par les boules ouvertes $B(x,r) = \Big\{  y : y\in E, d(x,y)<r\Big\}$ ?

:::

Nous sommes maintenant prêts à poser le cadre de la modélisation stochastique. L'espace de jeu
est toujours un espace mesurable.

::: {#def-measspace}

### Espace mesurable

Un univers $\Omega$ muni d'une $\sigma$-algèbre de sous-ensembles $\mathcal{F}$
est appelé espace mesurable. On le note $(\Omega, \mathcal{F})$.

:::

<p>

::: {#exm-measurable-spaces} 

- Si $\Omega$ est un ensemble dénombrable ou fini, alors $(\Omega, 2^\Omega)$ est
un espace mesurable.
- Si $\Omega=\mathbb{R}$, alors $(\mathbb{R}, \mathcal{B}({\mathbb{R}}))$ est un espace mesurable.

:::

Jusqu'ici, nous n'avons pas parlé de théorie des probabilités, mais
nous sommes maintenant en mesure de définir les lois de probabilité et de les manipuler.



## Mesures positives et lois de probabilité  {#sec-distribution}


Une _loi de probabilité_ envoie une $\sigma$-algèbre dans $[0,1]$. C'est
un cas particulier d'un concept plus général appelé _mesure_. Nous énonçons ou rappelons
des notions importantes de la théorie de la mesure. L'idée clé sous-jacente à l'élaboration de la théorie de la mesure
est qu'il faut se garder de vouloir mesurer _tous_ les sous-ensembles d'un univers (sauf si cet univers
est dénombrable). Les tentatives de mesurer tous les sous-ensembles de $\mathbb{R}$ mènent à des paradoxes et sont de peu
d'utilité pratique. La théorie de la mesure commence par reconnaître les propriétés souhaitables que toute mesure utile
doit posséder, puis elle construit des objets satisfaisant ces propriétés sur des $\sigma$-algèbres d'événements aussi grandes que possible,
par exemple sur les $\sigma$-algèbres boréliennes.

Cela motive la définition de la $\sigma$-additivité.

::: {#def-sigadd} 

### $\sigma$-additivité

Étant donnés $\Omega$ et $\mathcal{A} \subseteq 2^\Omega$, une fonction $\mu$ envoyant
$\mathcal{A}$ dans $[0,\infty) \cup \{ \infty\}$ est dite $\sigma$-additive sur $\mathcal{A}$ si pour toute collection dénombrable de sous-ensembles *deux à deux disjoints* $(A_n)_{n \in \mathbb{N}} \in \mathcal{A}$,
avec $\cup_n A_n \in \mathcal{A}$, on a
$$\mu (\cup_{n \in \mathbb{N}} A_n) = \sum_{n \in \mathbb{N}} \mu(A_n)  \, .$$

:::

Remarquons que si $\mathcal{F}$ est une $\sigma$-algèbre, $\Big(\cup_{n \in \mathbb{N}} A_n\Big) \in \mathcal{F}$.
La $\sigma$-additivité s'accorde bien avec les $\sigma$-algèbres, mais il est légitime de définir la $\sigma$-additivité par rapport à des collections de sous-ensembles plus générales.

<br><p></p>

::: {#prp-sigma-add-continuity}

Étant donnés $\Omega$, une $\sigma$-algèbre $\mathcal{A} \subseteq 2^\Omega$, une fonction $\sigma$-additive $\mu$ envoyant $\mathcal{A}$ dans $[0,\infty) \cup \{\infty\}$ avec $\mu(\emptyset)=0$ satisfait

a. pour toute suite *croissante* $(A_n)_{n \in \mathbb{N}}$ d'éléments de $\mathcal{A}$
    
    $$\lim_n \mu(A_n) = \mu\left(\cup_{n} A_n\right)$$

a. pour toute suite *décroissante* $(A_n)_{n \in \mathbb{N}}$ d'éléments de $\mathcal{A}$, si $\mu(A_n)< \infty$ pour un certain $n$,

    $$\lim_n \mu(A_n) = \mu\left(\cap_{n} A_n\right)$$

:::


::: {.proof}

a.) Posons $B_{1} = A_1$, et $B_{n+1} =  A_{n+1} \setminus A_n$ pour chaque $n$ ; alors $(B_n)_n$ est une suite d'éléments de $\mathcal{A}$ deux à deux disjoints. On a $\cup_n B_n = \cup_n A_n$ et, par $\sigma$-additivité, $\mu(\cup_n A_n) = \sum_n \mu(B_n)$

$$\sum_{n\leq m} \mu(B_n) = \mu\left(\cup_{n\leq m} B_m\right) = \mu(A_m)$$

D'où $\lim_{m\to \infty} \mu(A_m) = \sum_{n\in \mathbb{N}} \mu(B_n)= \mu(\cup_n A_n)$

b.) Le second énoncé se démontre de façon analogue (mais demande un peu plus de soin). Sans perte de généralité, on suppose $\mu(A_1)< \infty$.

La suite $(\mu(A_n))_n$ est positive ou nulle et décroissante ; elle admet une limite positive ou nulle $m$, et comme $\cap_{n=1}^\infty A_n \subseteq A_m$ pour tout $m$,  $\mu(\cap_{n=1}^\infty) A_n) \leq m$.  Il reste à vérifier que l'égalité a lieu.

Sans perte de généralité, on peut de plus supposer que $\cap_{n=1}^\infty A_n = \emptyset$, car en retranchant $\cap_{n=1}^\infty A_n$ de chaque $A_n$, on obtient une suite décroissante de sous-ensembles d'intersection vide. Alors, pour chaque $m$
$$A_m = \cup_{n=m}^\infty (A_n \setminus A_{n+1})$$
puisque tout $\omega \in A_m$ doit appartenir à un certain $A_n \setminus A_{n+1}$ pour un $n \geq m$.

D'où, par $\sigma$-additivité,  $\sum_{n=1}^\infty \mu(A_n \setminus A_{n+1}) = \mu(A_1) < \infty$.
Ainsi, comme restes d'une série convergente, $\mu(A_m) = \sum_{n=m}^\infty \mu(A_n \setminus A_{n+1})$ tend vers $0$.

On a établi $\lim_{m \to \infty} \mu(A_m) = 0.$
  
$\Box$

:::

::: {#def-pmeasure} 

### Mesure positive

Étant donné un espace mesurable $(\Omega, \mathcal{F})$, une fonction $\sigma$-additive $\mu$ envoyant
$\mathcal{F}$ dans $[0,\infty)\cup \{\infty\}$  est appelée  _mesure positive_ sur $(\Omega, \mathcal{F})$ si $\mu(\emptyset)=0$.

Le triplet $(\Omega, \mathcal{F}, \mu)$ est appelé espace mesuré.

:::

Lorsque $\mu(\Omega)$ est fini, on dit que $\mu$ est une mesure positive *finie*.


::: {#exr-fundspace} 

Soit $\Omega = \{0,1\}^*$ l'ensemble des suites infinies de $0$ et de $1$ (indicées
  à partir de $1$).
Soit $\mathcal{F}_n \subseteq 2^\Omega$ la $\sigma$-algèbre engendrée par
les événements de la forme : $\{ \omega : \omega \in \Omega, \omega_i = 1\}$
pour $1\leq i\leq n$.

- Définir une fonction $\sigma$-additive sur $(\Omega, \mathcal{F}_n)$.
- Quelle est la $\sigma$-algèbre engendrée par $\cup_{n\geq 1} \mathcal{F}_n$ ?
- Peut-on définir une fonction $\sigma$-additive sur $(\Omega, \sigma(\cup_{n\geq 1} \mathcal{F}_n))$ ?

:::

<p>
Une mesure positive $\mu$ n'est pas nécessairement une loi de probabilité. Par exemple,
la _mesure de comptage_ $\mu$ sur $\mathbb{N}$  satisfait $\mu(A) = |A|$ pour tout $A \subseteq \mathbb{N}$, si bien que $\mu(\mathbb{N})=\infty.$


<p>

::: {#def-probmeasure} 

### Loi de probabilité

Étant donné un espace mesurable $(\Omega, \mathcal{F})$, une fonction $\mu$ envoyant
$\mathcal{F}$ dans $[0,\infty)$ est une loi de probabilité sur $(\Omega, \mathcal{F})$  si

1. $\mu$ est une mesure positive sur $(\Omega, \mathcal{F})$  et
1. $\mu(\Omega)=1$.

:::

::: {#exr-challenge}
 
Si l'on pense que $(\mathbb{R}, 2^{\mathbb{R}})$ est un espace mesurable, définir une mesure $\sigma$-additive dessus. Tenter même de définir une mesure de probabilité.

:::


::: {#rem-sigma-add} 

La notion de $\sigma$-additivité est strictement plus forte que l'additivité finie.

En admettant l'*axiome du choix* (comme d'habitude en probabilités), il existe une fonction $\mu$
qui envoie $2^{\mathbb{N}}$ dans $[0,1]$, qui est additive ($\mu(A \cup B)= \mu(A) + \mu(B)$ pour tous $A, B$ avec $A\cap B=\emptyset$),
nulle sur tous les sous-ensembles finis de $\mathbb{N}$ et telle que $\mu(\mathbb{N})=1$. Une telle fonction n'est pas $\sigma$-additive.

:::

## Mesure de Lebesgue {#sec-lebesgue}

<p>

Nous tenons pour acquise l'existence de la mesure de Lebesgue. C'est le contenu du théorème suivant.

<p>

::: {#thm-lebesgue}

### Existence de la mesure de Lebesgue

Il existe une unique mesure $\sigma$-additive $\ell$ sur $(\mathbb{R}, \mathcal{B}(\mathbb{R}))$
telle que $\ell((a, b]) = b - a$ pour tous $a < b$ finis.

:::

<p>

Le [Théorème @thm-lebesgue] est typique des énoncés de la théorie de la mesure. Il définit un objet complexe
(une mesure) par sa trace sur une collection simple d'ensembles (les intervalles).

Les preuves du [Théorème @thm-lebesgue] peuvent être découpées en plusieurs morceaux significatifs. L'un d'eux peut être esquissé comme suit. On définit d'abord une fonction longueur sur les intervalles. On montre que cette fonction se prolonge en une fonction additive sur les unions finies, les intersections finies et les complémentaires d'intervalles.
On vérifie ensuite que le prolongement est en fait $\sigma$-additif sur la clôture
des intervalles sous les opérations ensemblistes finies (qui n'est pas une $\sigma$-algèbre).

Une fois ce prolongement additif construit, on utilise le théorème d'extension de Carathéodory ci-dessous pour montrer que la fonction longueur se prolonge en une fonction $\sigma$-additive sur la $\sigma$-algèbre engendrée par les intervalles (la $\sigma$-algèbre borélienne).

Il reste alors à vérifier que le prolongement est unique. Cela peut se faire par un argument de classe génératrice, par exemple le _lemme de la classe monotone_ [Lemme @thm-monotoneclasslemma].

::: {#thm-caratheodory}

### Théorème d'extension de Carathéodory

Soit $\mathcal{A} \subseteq 2^{\Omega}$. On suppose que $\mathcal{A}$ contient $\emptyset, \Omega$, et qu'elle est stable par unions finies et par passage au complémentaire. On suppose que $\rho : \mathcal{A} \to [0, \infty]$ est $\sigma$-additive sur $\mathcal{A}$.

Alors il existe une mesure $\mu$  sur $\sigma(\mathcal{A})$ telle que $\mu(A)=\rho(A)$ pour tout $A \in \mathcal{A}$.

:::

Le théorème d'existence de la mesure de Lebesgue garantit que l'on peut définir
la loi de probabilité uniforme sur un intervalle fini $[a,b]$. Si
l'on note $\ell$ la mesure de Lebesgue, la loi de probabilité uniforme
sur $[a,b]$ attribue la probabilité


$$
P(A) = \frac{\ell(A)}{b-a} = \frac{\ell(A)}{\ell([a,b])}
$$
 

à tout $A \in \mathcal{B}(\mathbb{R}) \cap [a,b]$.


<br><p></p>

La loi uniforme sur $([0,1], \mathcal{B}([0,1]))$ a l'apparence
d'une curiosité académique sans utilité pratique. Cette opinion superficielle doit être dissipée.
À partir d'un générateur de la loi uniforme, il est possible de construire
un générateur pour n'importe quelle loi de probabilité sur $(\mathbb{R}, \mathcal{B}(\mathbb{R}))$.
Cela peut se faire à l'aide d'un procédé appelé _transformation quantile_. En ce sens,
la loi uniforme est la mère de toutes les lois.

Une issue $\omega$ de la loi uniforme est un nombre réel. À quoi ressemble une
issue typique ? Un nombre réel $\omega \in [0,1]$ admet des développements binaires : $\omega = \sum_{i=1}^\infty b_i 2^{-1}$
avec $b_i \in \{0,1\}$. Quelle est la probabilité qu'il existe un unique développement binaire ?
Vérifier d'abord que cette probabilité est bien définie.
En supposant que le développement binaire est unique, $\omega$ est dit _normal_  si
$\lim_n \frac{1}{n}\sum_{i=1}^n b_i(\omega) = 1/2$. La probabilité d'obtenir un nombre normal
est-elle bien définie ? Si oui, la calculer.

<br><p></p>

::: {#exr-}

Vérifier que $\mathcal{B}(\mathbb{R}) \cap [a,b] =  \Big\{ A \cap [a,b] : A \in \mathcal{B}(\mathbb{R}) \Big\}$
est la $\sigma$-algèbre engendrée par la trace de la topologie usuelle de $\mathbb{R}$ sur $[a,b]$.

:::

Le théorème d'existence de Lebesgue peut être étendu. En effet, toute définition raisonnable
de la longueur d'un intervalle peut servir de point de départ.

Rappelons qu'une fonction réelle est càdlàg si elle est continue à droite en tout point
et admet des limites à gauche en tout point.

Le théorème suivant peut être établi d'une façon parallèle à la construction
de la mesure de Lebesgue.

<br><p></p>

::: {#thm-dudley3-1-3}

Toute fonction càdlàg croissante $F$ sur $\mathbb{R}$ définit une mesure $\sigma$-additive
$\mu$ sur $(\mathbb{R}, \mathcal{B}(\mathbb{R}))$ qui satisfait :

$$
\mu((a, b]) = F(b) - F(a)
$$

:::


<br><p></p>

On retrouve le théorème d'existence de Lebesgue en prenant $F(x)=x$.

Si l'on se restreint aux fonctions $F$ qui satisfont $\lim_{x \to -\infty} F(x)=0$
et $\lim_{x \to \infty} F(x)=1$, le Théorème @thm-dudley3-1-3 définit
des lois de probabilité par l'intermédiaire de leurs _fonctions de répartition_
(plus de détails sur ce sujet dans @sec-distribfun).

<br><p></p>

::: {#exr-dudley3-1-3}

Faut-il vraiment supposer que la fonction $F$ admet des limites à gauche dans le Théorème @thm-dudley3-1-3 ?

:::

<br><p></p>


## Fonctions mesurables et variables aléatoires {#sec-measurablefunctionsrv}

Jusqu'ici, nous n'avons parlé que de probabilités et de mesures d'ensembles (d'événements). Comme
la modélisation stochastique est au fondement de l'analyse quantitative, nous introduisons
la notion de fonction mesurable.
Cela nous permet de traiter des fonctions numériques qui envoient les issues dans $\mathbb{R}$
ou $\mathbb{R}^d$.

Toute fonction numérique n'est pas mesurable. Pour définir ce que l'on appelle une fonction
mesurable, nous avons besoin de la notion d'_image inverse_ ou de _préimage_.

::: {#def-preimage} 

### Image inverse

Soit $f$ une fonction de $\mathcal{X}$ vers $\mathcal{Y}$, on note $f^{-1}$
la fonction qui envoie $2^{\mathcal{Y}}$ dans $2^{\mathcal{X}}$ définie par

\begin{align*}
f^{-1}: \qquad 2^{\mathcal{Y}} & \rightarrow  2^{\mathcal{X}} \\
B & \mapsto f^{-1}(B) = \Big\{ x : x \in \mathcal{X}, f(x) \in B \Big\} \, .
\end{align*}

L'ensemble $f^{-1}(B)$ est appelé _préimage_ ou _image inverse_ de $B$ par $f$.

:::


Remarquons que $f^{-1}$ ne désigne pas l'inverse de la fonction $f$, qui peut ne pas être injective.
Dans ce cours, $f^{-1}$ est une fonction d'ensembles de l'ensemble des parties de l'ensemble d'arrivée de $f$ vers l'ensemble des parties de l'ensemble de départ de $f$. La fonction inverse, si elle existe (ou la fonction inverse généralisée) est notée $f^\leftarrow$. La fonction inverse, lorsqu'elle existe, envoie $f(\mathcal{X})\subseteq \mathcal{Y}$ dans $\mathcal{X}$.

::: {#exm-ideal-hashing} 

Rappelons le cadre du hachage idéalisé de @sec-hashing.
Soit $\Omega$ l'ensemble des fonctions de $1, \ldots, n$  vers $1, \ldots, m$
(on suppose $n \leq m$). Pour $\omega \in \Omega$ ($\omega$ est une fonction, mais c'est
aussi une suite de longueur $n$ à valeurs dans $1, \ldots, m$), soit $f(\omega)$ le
nombre de valeurs de $1, \ldots, m$ qui n'apparaissent pas dans $\omega$
(le nombre d'urnes vides dans l'allocation définie par $\omega$).  La fonction
$f$ est une fonction numérique définie sur $\Omega=\{1, \ldots, m\}^n$.
Pour $B \in \mathbb{N}$, $f^{-1}(B)$ est le sous-ensemble des allocations
qui ont $k$ urnes vides, $k \in B$.

:::

L'opération d'image inverse se comporte bien vis-à-vis des opérations ensemblistes.

Les propriétés élémentaires des fonctions mesurables découlent des propriétés des
images inverses. L'image inverse préserve les opérations ensemblistes.

::: {#prp-propinvimage}

Soit $f: E \mapsto F$, alors pour $A, B, A_1, \ldots,A_n , \ldots   \subseteq F$,

\begin{align*}
f^{-1}(A \cup B) & = f^{-1}(A) \cup f^{-1}(B) \\
f^{-1}(A \cap B) & = f^{-1}(A) \cap f^{-1}(B) \\
f^{-1}(\cup_{n \in \mathbb{N}}A_n ) & = \cup_{n \in \mathbb{N}} f^{-1}(A_n) \\
f^{-1}(\cap_{n \in \mathbb{N}}A_n ) & = \cap_{n \in \mathbb{N}} f^{-1}(A_n) \\
f^{-1}(F \setminus A) & =  f^{-1}(F) \setminus f^{-1}(A)
\end{align*}

:::

<br><p></p>

::: {#exr-propinvimage}

Vérifier @prp-propinvimage

:::

<br><p></p>

::: {#cor-sigma-reimages}

Prendre les images inverses des éléments d'une $\sigma$-algèbre définit une
$\sigma$-algèbre.

:::

Une autre proposition utile est la suivante : la collection des images d'une $\sigma$-algèbre est une $\sigma$-algèbre.
Cette proposition facilite grandement la résolution de @exr-summeasurable,  @exr-compmeasurable, ...

::: {#prp-propinvimage-sigma-algebra}

Soit $(\Omega, \mathcal{F})$ un espace mesurable et $\Omega'$ un ensemble, et soit $f$ une application de $\Omega$ dans $\Omega'$.
Alors
$$\left\{ B : B \subseteq \Omega', f^{-1}(B) \in \mathcal{F} \right\}$$
est une $\sigma$-algèbre de sous-ensembles de $\Omega'$.

:::


:::  {.proof}

Soit
$$\mathcal{B} = \left\{ B : B \subseteq \Omega', f^{-1}(B) \in \mathcal{F} \right\}$$

- $f^{-1}(\emptyset) = \emptyset \in \mathcal{F}$, $\emptyset \in \mathcal{B}$ ;
- $f^{-1}(\Omega') = \Omega \in \mathcal{F}$, d'où $\Omega'\in \mathcal{B}$ ;
- Si $B_1, \ldots, B_n, \ldots  \in \mathcal{B}$, alors $f^{-1}(\cup_n B_n ) = \cup_n f^{-1}(B_n) \in \mathcal{F}$ car $\mathcal{F}$ est une $\sigma$-algèbre, d'où $\cup_n B_n \in \mathcal{B}$ ;
- Si $B \in \mathcal{B}$, alors $f^{-1}(\Omega' \setminus B) =  f^{-1}(\Omega') \setminus f^{-1}(B) = \Omega \setminus f^{-1}(B) \in \mathcal{F}$ car $\mathcal{F}$ est une $\sigma$-algèbre, d'où $\Omega' \setminus B \in \mathcal{B}$.

$\mathcal{B}$ possède toutes les propriétés des $\sigma$-algèbres.


$\Box$

:::




::: {#prp-preimage-generation}

Soit $(\Omega, \mathcal{F})$ un espace mesurable, soit  $\Omega'$  un ensemble,  soit $\mathcal{B} \subseteq \mathcal{P}(\Omega')$.

Soit $f : \Omega \to \Omega'$.

Si $f^{-1}(B) \in \mathcal{F}$ pour tout $B \in \mathcal{B}$, alors $f^{-1}(C) \in \mathcal{F}$ pour tout $C \in \sigma\left(\mathcal{B}\right)$.

::: 


::: {.proof}

L'ensemble
$$\left\{ B : B \subseteq \Omega', f^{-1}(B) \in \mathcal{F} \right\}$$
est une $\sigma$-algèbre d'après @prp-propinvimage-sigma-algebra . Cette $\sigma$-algèbre contient tous les éléments de $\mathcal{B}$ et est donc plus grande que $\sigma(\mathcal{B})$.

$\Box$
:::

Nous définissons maintenant les fonctions mesurables. En probabilités, les *variables aléatoires* sont des *fonctions mesurables*.


::: {#def-measfunc} 

### Fonctions mesurables

Soient $(\Omega, \mathcal{F})$ et $(\Omega', \mathcal{G})$ deux espaces mesurables.

Une fonction $f: \Omega \to \Omega'$ est dite $\mathcal{F}/\mathcal{G}$-mesurable

si et seulement si

pour tout $B \in \mathcal{G}$, $f^{-1}(B) \in \mathcal{F}$.

:::

<p>


On se trouve souvent face à des questions du type : une certaine $f$ est-elle $\mathcal{F}/\mathcal{G}$-mesurable ?
Il existe de nombreuses conditions suffisantes classiques.


::: {#exr-continuous-measurable}

Vérifier que si $\Omega$ est un espace topologique et $\mathcal{F}$ la
$\sigma$-algèbre borélienne associée, alors toute fonction continue de $\Omega$ vers $\mathbb{R}$
est mesurable.

:::


::: {#exr-borel-continuous-measurable}

Si $\Omega=\mathbb{R}^d$ est muni de la $\sigma$-algèbre borélienne, est-ce la plus petite
$\sigma$-algèbre qui rende toutes les fonctions continues mesurables ?

:::

Afin de vérifier qu'une fonction de $\Omega$ vers $\mathbb{R}$ est $\mathcal{F}/\mathcal{B}(\mathbb{R})$-mesurable, il suffit de vérifier que l'image inverse d'une famille génératrice de la $\sigma$-algèbre borélienne est incluse dans $\mathcal{F}$ (d'après @prp-preimage-generation).

Comme les demi-droites engendrent la $\sigma$-algèbre borélienne, on sera heureux d'invoquer le corollaire suivant.

::: {#cor-checking-measurability}

Soit $(\Omega, \mathcal{F})$ un espace mesurable, soit $f$ une application de $\Omega$ dans $\mathbb{R}$.

Alors $f$ est $\mathcal{F}/\mathcal{B}(\mathbb{R})$-mesurable

si et seulement si

pour toute demi-droite $(-\infty, x[ \subseteq \mathbb{R}$, l'ensemble $f^{-1}((-\infty, x[)$ appartient à $\mathcal{F}$.


:::


Nous énonçons maintenant quelques propriétés supplémentaires des fonctions mesurables. On les résume d'ordinaire par l'affirmation un peu vague *l'ensemble des fonctions mesurables est stable par les opérations usuelles de l'analyse*.


::: {#prp-limmeasurable}

La limite ponctuelle de fonctions mesurables est une fonction mesurable :

si $(f_n)_n$ est une suite de fonctions mesurables de $(\Omega, \mathcal{F})$
vers $(\mathcal{X}, \mathcal{G})$, et $f_n \to f$ ponctuellement, alors $f$ est une fonction mesurable.

:::

<p>
::: {#exr-limmeasurable}

Démontrer @prp-limmeasurable

:::

<p>

Si l'on considère des fonctions mesurables à valeurs réelles, on peut énoncer

::: {#prp-summeasurable}

La somme de fonctions mesurables est une fonction mesurable :
si $f, g$ sont des fonctions mesurables de $(\Omega, \mathcal{F})$
vers $(\mathbb{R}, \mathcal{B}(\mathbb{R}))$, alors $a f + b g$ est une fonction mesurable pour tous $a,b \in \mathbb{R}$.

:::


::: {#exr-summeasurable}

Démontrer @prp-summeasurable.

Indication : traiter d'abord le cas où $f,g$ sont à valeurs dans $[0,\infty)$, puis utiliser @cor-checking-measurability.

:::
<p>



::: {#prp-compmeasurable}

La composition de fonctions mesurables est une fonction mesurable :

si $f$ est une fonction mesurable de $(\Omega, \mathcal{F})$ vers $(\mathcal{X}, \mathcal{G})$,
et $g$ est une fonction mesurable de $(\mathcal{X}, \mathcal{G})$ vers $(\mathcal{Y}, \mathcal{H})$, alors $g \circ f$
($g \circ f(\omega) = g(f(\omega))$ pour tout $\omega$)
est une fonction mesurable de $(\Omega, \mathcal{F})$ vers $(\mathcal{Y}, \mathcal{H})$.

:::
<br><p>

::: {#exr-compmeasurable}

Démontrer @prp-compmeasurable.

:::

<br><p>

<p></p>

## Variables aléatoires générales  {#sec-randomvariablesperse}

Une variable aléatoire réelle n'est ni une variable, ni aléatoire.
Une variable aléatoire réelle est une fonction mesurable d'un
espace mesurable vers la droite réelle munie de la
$\sigma$-algèbre borélienne. Il n'y a rien d'aléatoire dans une variable aléatoire.

::: {#def-realrv}

### Variable aléatoire à valeurs réelles

Étant donné un espace mesurable $(\Omega, \mathbb{F})$,
une application $X$ de $\Omega$ vers $\mathbb{R}$ est une variable aléatoire à valeurs réelles
si pour tout $B \in \mathcal{B}(\mathbb{R})$
l'image inverse de $B$ :

$$
X^{-1}(B) = \{ \omega : \omega \in \Omega, X(\omega) \in {B}\}
$$

appartient à $\mathcal{F}$.

Une variable aléatoire est une fonction $\mathbb{F}/\mathcal{B}(\mathbb{R})$-mesurable.

:::


Une fois qu'un espace mesurable est muni d'une loi de probabilité, il est possible
de définir la loi (de probabilité) d'une variable aléatoire.

::: {#def-disrv}

Étant donnés $(\Omega, \mathcal{F}, P)$ et une variable aléatoire réelle $X$,
la loi ou loi de probabilité de $X$, notée $P \circ X^{-1}$, est la loi de
probabilité sur $(\mathbb{R}, \mathcal{B}(\mathbb{R}))$  définie par

$$
(P \circ X^{-1})(B) =  P(X^{-1}(B)) \quad \text{pour tout } B \in \mathcal{B}(\mathbb{R}).
$$


:::



Les variables aléatoires peuvent être à valeurs vectorielles, à valeurs dans un espace de fonctions, _etc_.
Les variables aléatoires générales sont définies comme des fonctions mesurables
entre espaces mesurables.

::: {#def-rv} 

### Variable aléatoire

Étant donnés deux espaces mesurables $(\Omega, \mathcal{F})$ et $(\Omega', \mathcal{G})$,
une application $X$ de $\Omega$ vers $\Omega'$ est une variable aléatoire $\mathcal{F}/\mathcal{G}$ si
pour tout $B \in \mathcal{G}$ l'image inverse de $B$ :

$$
X^{-1}(B) = \{ \omega : \omega \in \Omega, X(\omega) \in {B}\}
$$

appartient à $\mathcal{F}$.

:::


Les variables aléatoires à valeurs réelles envoient des lois de probabilité vers des lois de probabilité sur la droite réelle.
La section suivante est consacrée à des constructions spécifiques de lois de probabilité sur la droite réelle.

<p><p>

## Lois de probabilité sur la droite réelle  {#sec-distribfun}

Une loi de probabilité est un objet complexe : elle envoie une vaste collection
d'ensembles (une $\sigma$-algèbre) dans $[0,1]$. Heureusement, il est possible
de caractériser une loi de probabilité par des objets plus simples. Si l'on se restreint aux
lois de probabilité sur $(\mathbb{R}, \mathcal{B}(\mathbb{R}))$,
elles peuvent être caractérisées par des fonctions réelles sur $\mathbb{R}$.


::: {#def-distrib-fun} 

### Fonction de répartition

Étant donnée une loi de probabilité $P$ sur $(\mathbb{R}, \mathcal{B}(\mathbb{R}))$,
la *fonction de répartition*
$F$ de $P$ envoie $\mathbb{R}$ dans $[0,1]$ ; elle est définie par

$$
x \mapsto F(x) = P(-\infty, x].
$$


:::

Une loi de probabilité définit une unique fonction de répartition. Ce qui est peut-être surprenant,
c'est qu'une fonction de répartition définit une unique loi de probabilité.

La proposition suivante résume les propriétés caractéristiques des fonctions de répartition.

::: {#prp-prop-distrib-function}

Soit $F$ une fonction de $\mathbb{R}$ vers $[0,1]$.

La fonction $F$ est la fonction de répartition d'une loi de probabilité sur $(\mathbb{R}, \mathcal{B}(\mathbb{R}))$ si et seulement si les cinq propriétés suivantes sont satisfaites :

1. $F$ est croissante,
1. $F$ est continue à droite
1. $\lim_{y \nearrow x} F(y)$ existe en tout $x \in \mathbb{R}$ ($F$ admet des limites à gauche en tout point)
1. $\lim_{x \to -\infty}F(x)=0$
1. $\lim_{x \to \infty} F(x)= 1.$

:::

C'est une reformulation de @thm-dudley3-1-3.


::: {.proof}  (sens seulement si)

Supposons que $F$ est la fonction de répartition d'une loi de probabilité $P$ sur $(\mathbb{R}, \mathcal{B}(\mathbb{R}))$.

1. Si $s \leq t$, $(-\infty, s] \subseteq (-\infty, t]$, donc $F(s)=P(-\infty, s] \leq P(-\infty, t]=F(t)$.
2. Il suffit de vérifier que $t_n \searrow_{n \to \infty} t$ entraîne $F(t_n) \searrow_{n \to \infty} F(t)$. Cela découle du point b) de @prp-sigma-add-continuity.
3. Si $t_n \searrow_{n \to \infty} t$, $(F(t_n))_n$ est une suite bornée croissante ; elle admet une limite finie égale à $P(-infty, t[ \leq F(t)$. C'est une conséquence du point a) de  @prp-sigma-add-continuity. L'égalité a lieu si et seulement si $P(-\infty,t] - P(-\infty, P\{t\}=0$.
4. C'est une conséquence du point b) de  @prp-sigma-add-continuity.
5. C'est une conséquence du point a) de  @prp-sigma-add-continuity.

$\Box$

:::

La preuve du sens *si* est reportée à l'étude des fonctions quantile dans @sec-chap-quantiles.

Comme sous-produit de la preuve du point 3) dans @prp-prop-distrib-function, on obtient

::: {#cor-diffuse-distrib-function}

Soit $F$ la fonction de répartition d'une loi de probabilité $P$ sur $(\mathbb{R}, \mathcal{B}(\mathbb{R})$.

$F$ est continue si et seulement si pour tout $x \in \mathbb{R}$, $P\{x\}=0$.

:::



La Figure @fig-distribpoisson montre la fonction de répartition
des lois de Poisson pour différentes valeurs du paramètre (voir les Sections @sec-conv2poisson
et @sec-poisson pour plus de détails sur les lois de Poisson).
Pour le paramètre $\mu$, $F_{\mu}(x) = \sum_{k \leq x}  \mathrm{e}^{-\mu} \frac{\mu^k}{k!}$.



<!-- ::: {#fig-distribpoisson} -->

```{r}
#| echo: false
#| message: false
#| warning: false
#| label: fig-distribpoisson
#| 
#| fig-cap: |
#|   Fonctions de répartition de lois de Poisson pour
#|   différents paramètres.
#|   On observe que, apparemment, $\mu \leq \nu \Rightarrow F_{\mu} \geq F_{\nu}$.
#|   Comment établiriez-vous cette propriété de domination ?


x = as.integer(seq(0, 20, by=1))
lambdas =  c(1, 5, 10)

df <- as.data.frame(c(list("x"=x),
                      lambdas |> purrr::map(.f = function(p) ppois(x, p))))

names(df) <- c("k", format(lambdas, digits=2))

df <- tidyr::gather(df, key="lambda", value="cdf", -k)

df <- df  |>
          dplyr::mutate(kend = ifelse(k<max(x), k+1, NA),
                 cdfend = ifelse(k<max(x), cdf, NA))

p <- df |>
     ggplot2::ggplot() +
     ggplot2::aes(x=k, y=cdf, xend=kend, yend=cdfend, linetype=lambda)+
     ggplot2::geom_segment() +
     ggplot2::geom_vline(ggplot2::aes(xintercept=k), linetype=2, color="grey") +
     ggplot2::geom_point(mapping=ggplot2::aes(x=k, y=cdf), size=.75, color=1) +
     ggplot2::scale_fill_discrete(guide=ggplot2::guide_legend(title="Parameter")) +
     ggplot2::xlab("k") +
     ggplot2::ylab("cdf") +
     ggplot2::xlim(xlim = c(-1, 20))

p

rm(df, lambdas, x)

# %%
```

<!-- ::: -->

## Le théorème de la classe monotone  {#sec-dynkin}

Le théorème/lemme de la classe monotone (théorème de Dynkin) est un exemple puissant d'*argument de classe génératrice*.  Il peut servir à montrer que deux mesures de probabilité sont égales (entre autres choses).


::: {#def-pi-class} 

### Classe $\pi$

Une collection $\mathcal{G}$ de sous-ensembles de $\Omega$ est dite
classe $\pi$ si :

- $\Omega \in \mathcal{G}$
- elle est stable par intersection finie
$$A, B \in \mathcal{G} \Rightarrow A \cap B \in \mathcal{G} \, .$$

:::

<p>

Une $\sigma$-algèbre est une classe $\pi$, mais la réciproque est fausse.

<p>

::: {#def-monotone-class} 

### Classe monotone

Une collection $\mathcal{M}$ de sous-ensembles de $\Omega$ est dite
classe monotone ou $\lambda$-système si elle satisfait les propriétés suivantes :

- $\Omega \in \mathcal{M}$
- Si $A, B \in \mathcal{M}$ et $A \subseteq B$, alors $B \setminus A \in \mathcal{M}$
- Si $A_n \in \mathcal{M}$ et $A_n \subseteq A_{n+1}$ pour tout $n \in \mathbb{N}$,
alors $\lim_n A_n = \cup_{n \in \mathbb{N}} A_n \in \mathcal{M}$.

:::

<p>
Une $\sigma$-algèbre est un $\lambda$-système.

<p>

L'intersection d'une collection de $\lambda$-systèmes est un $\lambda$-système.
Il est donc légitime de parler du plus petit $\lambda$-système
contenant une collection d'ensembles.

<p>

La proposition facile suivante rend les $\lambda$-systèmes très utiles lorsque
l'on veut vérifier que deux lois de probabilité sont égales.


::: {#prp-keyobservation}

La classe des ensembles sur lesquels deux lois de probabilité coïncident est un
$\lambda$-système.

:::


<p></p>


::: {.proof}

Soit $(\Omega, \mathcal{F})$ un espace mesurable. Soient $P, Q$ deux lois de
probabilité sur $(\Omega, \mathcal{F})$. Soit $\mathcal{C} \subseteq \mathcal{F}$ définie par

$$
\mathcal{C} = \Big\{ A : A \in \mathcal{F},  P(A)=Q(A) \Big\} \, .
$$

Par la définition même des mesures, on a $P(\Omega)=Q(\Omega)$, d'où $\Omega \in \mathcal{C}$.

Si $A \subseteq B$ appartiennent tous deux à $\mathcal{C}$, encore par la définition même des mesures,

$$
P (B \setminus A) = P(B) - P(A) = Q(B) - Q(A) = Q(B \setminus A) \, ,
$$

d'où $B\setminus A \subseteq \mathcal{C}$.

Soit $A_1 \subseteq A_2 \subseteq A_n \subseteq \ldots$ une suite croissante d'éléments de $\mathcal{C}$ ;
encore par la définition même des mesures,

$$
P(\cup_n A_n) = \lim_n \uparrow P(A_n) = \lim_n \uparrow Q(A_n) = Q(\cup_n A_n) \, .
$$

Donc $\mathcal{C}$ est stable par limites monotones.

  

:::

<p></p>



::: {#exr-keyobs} 

Que se passe-t-il si l'on considère les collections d'ensembles mesurables sur lesquels deux mesures sont égales ? Que se passe-t-il si l'on suppose que les deux mesures sont finies ? $\sigma$-finies

:::


::: {#def-sigfinite} 

### Mesures $\sigma$-finies

Une mesure $\mu$
sur $(\Omega, \mathcal{F})$ est $\sigma$-finie si et seulement s'il existe $(A_n)_n$ avec $\Omega \subseteq \cup_n A_n$
et $\mu(A_n) < \infty$ pour chaque $n$.

:::

Les mesures finies (ce qui englobe les mesures de probabilité) sont $\sigma$-finies. La mesure de
comptage sur $\mathbb{N}$ est $\sigma$-finie. La mesure de Lebesgue est $\sigma$-finie. La mesure de comptage sur $\mathbb{R}$ n'est pas $\sigma$-finie.

<p></p>

Que se passe-t-il si l'on suppose seulement que les deux mesures sont $\sigma$-finies ?

<br><p></p>


::: {#thm-monotoneclasslemma}

### Lemme de la classe monotone

Si $\mathcal{A}$ est un $\pi$-système dans $\Omega$ et $\mathcal{M}$ un $\lambda$-système
dans $\Omega$ tels que $\mathcal{A} \subseteq \mathcal{M}$, alors
la $\sigma$-algèbre engendrée par $\mathcal{A}$, $\sigma(A)$, est le plus petit $\lambda$-système
plus grand que $\mathcal{A}$ :
$$\sigma(\mathcal{A}) \subseteq \mathcal{M} \,.$$

:::

<p></p>

::: {.proof}

Soit $\mathcal{M}$ l'intersection de toutes les classes monotones qui contiennent
le $\pi$-système $\mathcal{A}$.
Comme une $\sigma$-algèbre est une classe monotone (un $\lambda$-système), on a $\mathcal{M} \subseteq \sigma(\mathcal{A})$ ; le seul point
à vérifier est $\sigma(\mathcal{A}) \subseteq \mathcal{M}$. Il suffit de vérifier
que $\mathcal{M}$ est bien une $\sigma$-algèbre.

Afin de vérifier que $\mathcal{M}$ est une $\sigma$-algèbre, il suffit de vérifier qu'elle
est stable par union finie, ou de façon équivalente par intersection finie.

Pour chaque $A \in \mathcal{A}$, soit $\mathcal{M}_A$ définie par
$$
\mathcal{M}_A = \Big\{ B : B \in \mathcal{M}, A \cap B \in \mathcal{M}\Big\} \, .
$$

Rappelons que $\mathcal{A}$ est un $\pi$-système, et $\mathcal{A} \subseteq \mathcal{M}$,
d'où $\mathcal{A} \subseteq \mathcal{M}_A$. Pour montrer que $\mathcal{M} = \mathcal{M}_A$,
il suffit de montrer que $\mathcal{M}_A$ est une classe monotone.

Si $(B_n)_n$ est une suite croissante d'éléments de $\mathcal{M}_A$, alors

$$
(\cup_n B_n) \cap A = \cup_n \Big(\underbrace{B_n \cap A }_{\in \mathcal{M}}\Big) \, ,
$$

le membre de droite appartient à $\mathcal{M}$ car $\mathcal{M}$ est monotone. Donc
$\mathcal{M}_A$ est stable par limite croissante monotone.


Pour vérifier la stabilité par passage au complémentaire, soient $B \subseteq C$ avec $B, C \in \mathcal{M}_A$. Comme

$$
 A \cap (C \setminus B) = \Big(\underbrace{A \cap C}_{\in \mathcal{M}}\Big) \setminus \Big(\underbrace{A \cap B}_{\in \mathcal{M}}\Big)
 ) \,
$$

la stabilité de $\mathcal{M}$ par passage au complémentaire entraîne $A \cap (C \setminus B) \in \mathcal{M}$
et $C \setminus B  \in \mathcal{M}_A.$

Soit maintenant $\mathcal{M}^{\circ}$ définie par
$$
\mathcal{M}^\circ = \Big\{  A : A \in \mathcal{M}, \forall B \in \mathcal{M},   A \cap B \in \mathcal{M} \Big\} \,.
$$

On vient d'établir que $\mathcal{A} \subseteq \mathcal{M}^{\circ}$.
Le même raisonnement permet de vérifier que $\mathcal{M}^\circ$ est également une classe monotone.
Cela montre que $\mathcal{M}^\circ= \mathcal{M}$.

Ceci achève la preuve.

  

:::


<br><p></p>

La combinaison de la [Proposition @prp-keyobservation] et du lemme de la classe monotone ([@thm-monotoneclasslemma]) mène au corollaire utile suivant.

<br><p></p>



::: {#prp-charaterize-distrib name="Caractérisation des lois de probabilité"}

Si deux probabilités $P, Q$ sur $(\Omega, \mathcal{F})$
coïncident sur un $\pi$-système $\mathcal{A}$
qui engendre $\mathcal{F}$ :

$$
\mathcal{A} \subseteq \{ A : A \in \mathcal{F}  \text{ et } P(A)=Q(A)\} \qquad\text{et} \qquad \mathcal{F} \subseteq \sigma(\mathcal{A})
$$

alors $P, Q$ coïncident sur $\mathcal{F}$.

:::

::: {#cor-cdf-charaterize-distrib name="Les fonctions de répartition caractérisent les lois de probabilité"}

Si deux probabilités $P, Q$ sur $(\mathbb{R}, \mathcal{B}(\mathbb{R}))$ ont la même fonction de répartition, alors $P=Q$.

:::

## Remarques bibliographiques  {#bibliolanguage}

Il existe de nombreux beaux ouvrages de théorie des probabilités. Ils s'adressent à
des publics différents. J'ai trouvé les suivants particulièrement utiles.

<!-- [Youssef (2019)](https://www.lpsm.paris/pageperso/youssef/Enseignement_files/M1-proba-2018.pdf)
est un recueil clair et concis de notes de cours conçu pour un cours de Probabilités de niveau Master I
substantiellement plus ambitieux que ce cours minimal. -->

@berger2021introduction adopte une approche très progressive et comporte de nombreux exemples. Il est recommandé aux étudiants surtout intéressés par les applications pratiques.

@MR1932358 propose un cours autonome d'analyse et de probabilités. L'ouvrage peut servir
à la fois d'introduction et d'ouvrage de référence. Outre des preuves soigneuses et transparentes, il
contient des notes historiques qui aident à comprendre les liens entre les résultats fondateurs.

@MR1873379 introduit la théorie de la mesure et de l'intégration à un public qui a déjà
été exposé à la théorie des probabilités discrètes et qui est familier du raisonnement
probabiliste.

@zbMATH06258045  est un traitement approfondi et pourtant très lisible de la théorie de la mesure et de l'intégration, avec des chapitres sur la théorie des probabilités et la théorie descriptive des ensembles.

@stein2009real  propose une construction vivante de la théorie de la mesure et de l'intégration.

@rudin1966  introduit la théorie de la mesure et de l'intégration à un public possédant un solide bagage d'analyse, et un intérêt pour l'analyse fonctionnelle.
