project:
  type: book
  

book:
  title: "MA1AY010 Class Notes"
  author: "Master I ISIFAR"
  date: "2025-09-15"
  downloads: [pdf]
  site-url: "https://s-v-b.github.io/MA1AY010-CN/"
  repo-url: https://github.com/s-v-b/MA1AY010-CN/
  repo-branch: main
  repo-actions: [edit, issue]
  # cover-image: cover.jpg
  # favicon: cover.jpg


  navbar:
    search: true
    
    
  
  chapters:
    - index.qmd
    - 01-intro.qmd
    - 02-language.qmd
    - 031-moments.qmd
    - 033-integration2moments.qmd
    - 03-families.qmd
    - 0225-pgf.qmd
    - 022-product-measures.qmd
    - 021-independence.qmd
    - 032-acfamilies.qmd
    - 023-discrete-condition.qmd
    - 06-conditioning.qmd
    - 04-characterizations.qmd
    - 041-characterization.qmd
    - 05-convergences-1.qmd
    - 08-convergence-3.qmd
#    - 08-convergence-3b.qmd
    - 09-gaussian-vectors.qmd

#    - summary.qmd
#    - references.qmd

# bibliography: references.bib

format:

  html:
    theme:
      - cosmo
      - brand
    favicon: images/UniversiteParis_monogramme_couleur_RVB.png
    
  pdf:
    documentclass: memoir
    classoption: [10pt, a4paper, twoside]
    mainfont: EB Garamond
    sansfont: Iwona Cond Medium
    papersize: A4
    include-in-header: 
      text: |
        % Remove slant in headers, use upright small caps
        \makepagestyle{mystyle}
        \makeevenhead{mystyle}{\scshape\small\leftmark}{}{}
        \makeoddhead{mystyle}{}{}{\scshape\small\rightmark}
        \makeevenfoot{mystyle}{\scshape\small ma1ay010}{\thepage}{\scshape\small m1 isifar}
        \makeoddfoot{mystyle}{\scshape\small m1 isifar}{\thepage}{\scshape\small ma1ay010}
        \pagestyle{mystyle}

filters:
  - callouty-theorem


callouty-theorem:
  thm:
    override-title: false # do not override the title of the callout (title won't show when `appearance` set to `simple` or `minimal`)
    callout: # parameters of the wrapping callout. see Quarto documentation of callouts for more details
      type: note
      appearance: minimal
  prp:
    override-title: false
    callout:
      type: note
      appearance: minimal
  lem:
    override-title: false
    callout:
      type: note
      appearance: minimal
  cor:
    override-title: false
    callout:
      type: note
      appearance: minimal
  def:
    override-title: false
    callout:
      type: note
      appearance: minimal
  exr:
    override-title: false
    callout:
      type: tip
      appearance: minimal
  
  # proof: # also support wrapping proof-like environments
  #   override-title: true # override the title of the callout by the name of the theorem
  #   callout:
  #     type: note
  #     appearance: default
  #     collapse: true
  #     icon: true
  # solution:
  #   override-title: true
  #   callout:
  #     type: note
  #     appearance: default
  #     collapse: true
  #     icon: true
  rem:
    override-title: false
    callout:
      type: tip
      appearance: minimal
      collapse: false
      icon: true

  # theorems types not specified in the metadata will be rendered as is


bibliography: ["stbib.bib", "book.bib", "packages.bib"]
biblio-style: apalike
link-citations: true
csl: "style/apa.csl"
editor: source
# always_allow_html: true


